import {
  StartupEntry,
  CentralBankRate,
  CloudProviderIndexEntry,
  JobListing,
  RateSnapshotPayload,
} from '../types';

export const INITIAL_STARTUPS: StartupEntry[] = [];

export const INITIAL_CENTRAL_BANK_RATES: CentralBankRate[] = [
  {
    id: 'cb-fed',
    bank_code: 'FED',
    bank_name: 'US Federal Reserve',
    country_or_region: 'United States',
    currency: 'USD',
    rate_instrument: 'Fed Funds Target (3.75%–4.00%)',
    current_rate: 4.00,
    previous_rate: 3.75,
    change_bps: 25,
    trend: 'up',
    inflation_yoy: 2.6,
    real_rate: 1.40,
    last_decision_date: '2026-09-16',
    next_meeting_date: '2026-11-05',
    official_source_url: 'https://www.federalreserve.gov/monetarypolicy/openmarket.htm',
    historical_12m: [3.75, 3.50, 3.50, 3.50, 3.75, 3.75, 4.00],
  },
  {
    id: 'cb-ecb',
    bank_code: 'ECB',
    bank_name: 'European Central Bank',
    country_or_region: 'Eurozone',
    currency: 'EUR',
    rate_instrument: 'Deposit Facility Rate',
    current_rate: 2.50,
    previous_rate: 2.25,
    change_bps: 25,
    trend: 'up',
    inflation_yoy: 2.1,
    real_rate: 0.40,
    last_decision_date: '2026-09-10',
    next_meeting_date: '2026-10-29',
    official_source_url: 'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html',
    historical_12m: [2.00, 2.00, 2.00, 2.25, 2.25, 2.25, 2.50],
  },
  {
    id: 'cb-cbn',
    bank_code: 'CBN',
    bank_name: 'Central Bank of Nigeria',
    country_or_region: 'Nigeria',
    currency: 'NGN',
    rate_instrument: 'Monetary Policy Rate (MPR)',
    current_rate: 23.00,
    previous_rate: 26.50,
    change_bps: -350,
    trend: 'down',
    inflation_yoy: 24.8,
    real_rate: -1.80,
    last_decision_date: '2026-09-22',
    next_meeting_date: '2026-11-24',
    official_source_url: 'https://www.cbn.gov.ng/rates/mnymp.asp',
    historical_12m: [27.25, 27.50, 27.50, 26.75, 26.50, 26.50, 23.00],
  },
  {
    id: 'cb-boe',
    bank_code: 'BoE',
    bank_name: 'Bank of England',
    country_or_region: 'United Kingdom',
    currency: 'GBP',
    rate_instrument: 'Official Bank Rate',
    current_rate: 3.75,
    previous_rate: 3.75,
    change_bps: 0,
    trend: 'hold',
    inflation_yoy: 3.1,
    real_rate: 0.65,
    last_decision_date: '2026-09-17',
    next_meeting_date: '2026-11-05',
    official_source_url: 'https://www.bankofengland.co.uk/monetary-policy/the-interest-rate-bank-rate',
    historical_12m: [4.00, 3.75, 3.75, 3.75, 3.75, 3.75, 3.75],
  },
  {
    id: 'cb-boj',
    bank_code: 'BoJ',
    bank_name: 'Bank of Japan',
    country_or_region: 'Japan',
    currency: 'JPY',
    rate_instrument: 'Uncollateralized Overnight Call Rate',
    current_rate: 1.25,
    previous_rate: 1.00,
    change_bps: 25,
    trend: 'up',
    inflation_yoy: 2.6,
    real_rate: -1.35,
    last_decision_date: '2026-09-18',
    next_meeting_date: '2026-10-30',
    official_source_url: 'https://www.boj.or.jp/en/mopo/index.htm',
    historical_12m: [0.25, 0.50, 0.50, 0.75, 1.00, 1.00, 1.25],
  },
  {
    id: 'cb-sarb',
    bank_code: 'SARB',
    bank_name: 'South African Reserve Bank',
    country_or_region: 'South Africa',
    currency: 'ZAR',
    rate_instrument: 'Monetary Policy Repo Rate',
    current_rate: 7.25,
    previous_rate: 7.00,
    change_bps: 25,
    trend: 'up',
    inflation_yoy: 4.4,
    real_rate: 2.85,
    last_decision_date: '2026-09-25',
    next_meeting_date: '2026-11-19',
    official_source_url: 'https://www.resbank.co.za/en/home/what-we-do/monetary-policy',
    historical_12m: [8.00, 7.75, 7.50, 7.25, 7.00, 7.00, 7.25],
  },
  {
    id: 'cb-cbk',
    bank_code: 'CBK',
    bank_name: 'Central Bank of Kenya',
    country_or_region: 'Kenya',
    currency: 'KES',
    rate_instrument: 'Central Bank Rate (CBR)',
    current_rate: 8.75,
    previous_rate: 8.75,
    change_bps: 0,
    trend: 'hold',
    inflation_yoy: 4.2,
    real_rate: 4.55,
    last_decision_date: '2026-08-11',
    next_meeting_date: '2026-10-13',
    official_source_url: 'https://www.centralbank.go.ke/rates/central-bank-rate/',
    historical_12m: [12.00, 11.25, 10.50, 9.50, 8.75, 8.75, 8.75],
  },
  {
    id: 'cb-rbi',
    bank_code: 'RBI',
    bank_name: 'Reserve Bank of India',
    country_or_region: 'India',
    currency: 'INR',
    rate_instrument: 'Policy Repo Rate',
    current_rate: 5.25,
    previous_rate: 5.25,
    change_bps: 0,
    trend: 'hold',
    inflation_yoy: 3.7,
    real_rate: 1.55,
    last_decision_date: '2026-08-05',
    next_meeting_date: '2026-10-07',
    official_source_url: 'https://www.rbi.org.in/',
    historical_12m: [6.50, 6.25, 6.00, 5.75, 5.50, 5.25, 5.25],
  },
];

export const INITIAL_CLOUD_PRICING_INDEX: CloudProviderIndexEntry[] = [
  {
    id: 'cp-aws',
    provider: 'AWS (Lambda + RDS + CloudFront)',
    tier_name: 'On-Demand Enterprise',
    category: 'Serverless Compute',
    serverless_per_1m_req: 0.20,
    compute_gb_sec: 0.00001667,
    db_storage_per_gb: 0.115,
    egress_per_gb: 0.09,
    free_egress_gb: 100,
    gpu_h100_hourly: 3.92,
    trend_30d: 'hold',
    notes: 'Includes 1M free Lambda requests/mo; NAT Gateway & cross-AZ transfer billed separately.',
    updated_at: '2026-09-28T00:00:00Z',
  },
  {
    id: 'cp-supabase',
    provider: 'Supabase (Pro / Scale)',
    tier_name: 'Pro Managed Postgres',
    category: 'Managed Postgres',
    serverless_per_1m_req: 2.00,
    compute_gb_sec: 0.000015,
    db_storage_per_gb: 0.125,
    egress_per_gb: 0.09,
    free_egress_gb: 250,
    gpu_h100_hourly: null,
    trend_30d: 'down',
    notes: '$25/mo base includes 8GB disk, 250GB cached/un-cached egress, and 100k MAU Auth.',
    updated_at: '2026-09-28T00:00:00Z',
  },
  {
    id: 'cp-vercel',
    provider: 'Vercel (Fluid Compute)',
    tier_name: 'Pro Team Plan',
    category: 'Serverless Compute',
    serverless_per_1m_req: 0.60,
    compute_gb_sec: 0.000018,
    db_storage_per_gb: 0.15,
    egress_per_gb: 0.15,
    free_egress_gb: 1000,
    gpu_h100_hourly: null,
    trend_30d: 'down',
    notes: 'Fluid Compute reduces idle I/O wait charges by up to 65% for AI streaming workloads.',
    updated_at: '2026-09-28T00:00:00Z',
  },
  {
    id: 'cp-cloudflare',
    provider: 'Cloudflare (Workers + R2 + D1)',
    tier_name: 'Workers Paid',
    category: 'Bandwidth & Egress',
    serverless_per_1m_req: 0.30,
    compute_gb_sec: 0.000012,
    db_storage_per_gb: 0.015,
    egress_per_gb: 0.00,
    free_egress_gb: 999999,
    gpu_h100_hourly: null,
    trend_30d: 'hold',
    notes: '$0.00 egress fee on R2 object storage; billed strictly on CPU milliseconds, not wall-clock wait.',
    updated_at: '2026-09-28T00:00:00Z',
  },
  {
    id: 'cp-gcp',
    provider: 'Google Cloud (Cloud Run + Cloud SQL)',
    tier_name: 'Pay-As-You-Go',
    category: 'AI GPU Compute',
    serverless_per_1m_req: 0.40,
    compute_gb_sec: 0.000018,
    db_storage_per_gb: 0.17,
    egress_per_gb: 0.12,
    free_egress_gb: 100,
    gpu_h100_hourly: 3.65,
    trend_30d: 'down',
    notes: 'Committed Use Discounts (CUD) lower A3 H100 Mega instance pricing by 42%.',
    updated_at: '2026-09-28T00:00:00Z',
  },
  {
    id: 'cp-neon',
    provider: 'Neon Serverless Postgres',
    tier_name: 'Scale Autoscaling',
    category: 'Managed Postgres',
    serverless_per_1m_req: 0.25,
    compute_gb_sec: 0.000016,
    db_storage_per_gb: 0.10,
    egress_per_gb: 0.09,
    free_egress_gb: 100,
    gpu_h100_hourly: null,
    trend_30d: 'down',
    notes: 'Scale-to-zero branching architecture with instant copy-on-write database clones for CI/CD.',
    updated_at: '2026-09-28T00:00:00Z',
  },
];

export const INITIAL_RATE_SNAPSHOT: RateSnapshotPayload = {
  id: 'snap-2026-10-01',
  source: 'n8n_automated_monetary_cloud_pipeline',
  recorded_at: '2026-10-01T06:00:00Z',
  central_bank_rates: INITIAL_CENTRAL_BANK_RATES,
  cloud_pricing_index: INITIAL_CLOUD_PRICING_INDEX,
};

export const INITIAL_JOBS: JobListing[] = [];
